name: Cancel

on:
  pull_request:
    branches: [master]

jobs:
  cancel:
    name: 'Cancel previous runs'
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.9.0
        with:
          workflow_id: node.js.yml
          access_token: ${{ secrets.GITHUB_TOKEN }}