
name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run 
    - run: npm test

    - name: Cypress run
      uses: cypress-io/github-action@v5
      with:
        start: npm run start
        wait-on: 'http://localhost:3000'
       
    - name: Create test summary
      uses: test-summary/action@v1.0
      if: always()
      with:
        paths: ./cypress/reports/junit/*.xml
  
    - name: Mochawesome reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: cypress-reports
        path: ./cypress/reports/mochawesomeReports    
       